language: python

branches:
  except:
    - gh-pages

python:
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"


install:
  - python setup.py install
  - pip install pytest pytest-cov pytest-pep8

script:
  - ./run-tests.sh dq

matrix:
  allow_failures:
    - python: "3.1"
    - python: "3.2"
    - python: "3.3"
